# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
# Theme Settings
minimal_mistakes_skin: "dark"

# Site Settings
locale: "en-US"
title: "Student Testimonials"
title_separator: "-"
description: "A collection of inspiring student testimonials."
url: "https://yourwebsiteurl.com" # Replace with your actual site URL
baseurl: "" # If deployed at the root, keep this blank
repository: "" # Optional GitHub repository
masthead_title: "Student Testimonials"

# Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/

# Collections
collections:
  testimonials:
    output: true
    permalink: /:collection/:name/

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Testimonials"
    url: "/testimonials/"
  - title: "About"
    url: "/about/"

# Site Author
author:
  name: "Your Name"
  bio: "Collecting student voices from around the globe."
  location: "Worldwide"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-profile"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yourname@example.com"

# Defaults
defaults:
  # For testimonials
  - scope:
      path: ""
      type: testimonials
    values:
      layout: single
      author_profile: false
      share: false
      comments: false

  # For blog posts (optional)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-profile"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yourname@example.com"

# Archives (Optional, for future use)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Output Settings
permalink: /:categories/:title/
timezone: "UTC"
